#!/bin/bash

echo ".... updating brew"
brew update && brew upgrade && brew cleanup

echo ".... installing tig"
brew install tig

echo ".... installing diff-so-fancy"
brew install diff-so-fancy

echo ".... installing autojump"
brew install autojump

echo ".... installing ag"
brew install ag

echo ".... installing wget"
brew install wget

echo ".... installing curl"
brew install curl

echo ".... installing htop"
brew install htop

echo ".... brew install hub"
brew install hub

echo ".... brew cleanup"
brew cleanup
